services:
  app:
    build: .
    image: ghcr.io/williamjacksn/jour
    ports:
      - 8080:8080
    volumes:
      - ./.local:/home/python/jour/.local

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/jour
    init: true
    volumes:
      - ./:/home/python/jour
